## Merge dataframes with outliers and cluster labels

In [26]:
import pandas as pd

In [27]:
data_with_outliers_labels = pd.read_csv('../data/transactions_with_outliers.csv')

data_with_cluster_labels = pd.read_csv('../data/df_labels_all_methods.csv', index_col=0)

In [28]:
data_with_outliers_labels.shape

(8500, 19)

In [29]:
cluster_labels = data_with_cluster_labels[['KMeans_label', 'labels_hierarchical_3c', 'labels_hierarchical_9c']]

In [30]:
data_all_labels = pd.concat([data_with_outliers_labels,cluster_labels], axis=1)
data_all_labels.shape

(8500, 22)

In [31]:
data_all_labels.to_csv('../data/labelled_transactions.csv', index=False)
data_all_labels

,balance_account,purchases_amount,paid_advance,full_purchases,balance_frequency_update,installments,purchases_frequency,full_purchases_frequency,purchases_installments_frequency,cash_advance_frequency,...,credit_limit,fixed_rate_period,payments,min_payments,full_payment_prc,Outlier_CBLOF,Outlier_IF,KMeans_label,labels_hierarchical_3c,labels_hierarchical_9c
0,9.298409,107.60,0.000000,0.00,0.909091,107.60,0.909091,0.000000,0.818182,0.000000,...,1000.0,11.0,89.868853,89.711672,0.428571,0,0,2,0,1
1,52.666422,150.30,0.000000,0.00,1.000000,150.30,1.000000,0.000000,0.833333,0.000000,...,1000.0,6.0,54.722514,82.955180,0.000000,0,0,2,0,1
2,1360.795674,0.00,462.861443,0.00,1.000000,0.00,0.000000,0.000000,0.000000,0.272727,...,1500.0,11.0,303.031979,443.781316,0.000000,0,0,2,0,1
3,2021.641161,363.18,0.000000,363.18,1.000000,0.00,1.000000,1.000000,0.000000,0.000000,...,2000.0,12.0,704.240770,795.859808,0.000000,0,0,2,0,1
4,22.322374,95.00,1162.045833,95.00,0.363636,0.00,0.083333,0.083333,0.000000,0.166667,...,2500.0,12.0,4094.261427,40.142262,0.000000,0,0,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8495,1127.607606,0.00,271.093275,0.00,1.000000,0.00,0.000000,0.000000,0.000000,0.083333,...,8500.0,12.0,662.387331,260.277533,0.000000,0,0,2,1,7
8496,21.409828,149.71,0.000000,0.00,1.000000,149.71,0.916667,0.000000,0.916667,0.000000,...,1500.0,12.0,141.974905,150.500248,0.166667,0,0,2,0,1
8497,0.000000,0.00,253.887233,0.00,0.000000,0.00,0.000000,0.000000,0.000000,0.111111,...,500.0,9.0,2437.932505,119.113995,0.000000,0,0,2,0,1
8498,1646.384530,1047.34,146.650389,1047.34,1.000000,0.00,0.583333,0.583333,0.000000,0.166667,...,3000.0,12.0,462.848132,497.408854,0.000000,0,0,2,0,1
8499,1861.087370,1752.06,0.000000,1417.18,1.000000,334.88,0.916667,0.583333,0.666667,0.000000,...,3500.0,12.0,737.941555,437.075647,0.000000,0,0,2,0,8